### ISSUE TITLE
linkplay' calls async_register from a thread at custom_components/linkplay/__init__.py, line 171: hass.services.async_register

### ISSUE THREAD

**Issue by calamarain** [nagyrobi/media_player.linkplay#137]
Recently, the linkplay integration for my Yamaha soundbar stopped working all together. I don't know when exactly, and have no idea what triggered it.

An error occurs when starting Home Assistant:
```
Logger: homeassistant.setup
Source: setup.py:404
First occurred: 10:21:18 (1 occurrences)
Last logged: 10:21:18

Error during setup of component linkplay
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linkplay/__init__.py", line 171, in setup
    hass.services.async_register(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2522, in async_register
    self._hass.verify_event_loop_thread("async_register")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'linkplay' calls async_register from a thread at custom_components/linkplay/__init__.py, line 171: hass.services.async_register(. Please report it to the author of the 'linkplay' custom integration.
```

```
Core 2024.5.0
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.0
```

Config
```
media_player:
  - platform: linkplay
    name: Luidspreker videoscherm
    host: 192.168.1.74
```

**Comment by nagyrobi** [comment]
You don't use the latest version...

**Comment by calamarain** [comment]
My bad, thanks for the reply. 🙂
