### ISSUE TITLE
After updating HA 2024.7 media player stopped working

### ISSUE THREAD

**Issue by cpmarexel2f** [nagyrobi/media_player.linkplay#146]
024-07-03 22:08:36.983 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up linkplay platform for media_player2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/linkplay/media_player.py", line 276, in async_setup_platform
    linkplay = LinkPlayDevice(name,
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linkplay/media_player.py", line 314, in __init__
    self._factory = UpnpFactory(requester, disable_unknown_out_argument_error=True)

**Comment by nagyrobi** [comment]
Fixed in https://github.com/nagyrobi/home-assistant-custom-components-linkplay/commit/e1d74c353c71b82b913d3b3f99440ec4daf37837. Please update.
