### ISSUE TITLE
Config fails

### ISSUE THREAD

**Issue by borgeST** [nagyrobi/media_player.linkplay#148]
Hey.

Check config throws errors when I try to configure integration.

Config:
`media_player:
  - platform: bluesound
    hosts:
      - host: 192.168.x.xx
        name: BK Stue
        port: 11000
      - host: 192.168.x.xxx

  - platform: linkplay
    host: 192.168.xx.xxx
    protocol: https
    name: Sound Room1
    volume_step: 10
    icecast_metadata: "StationNameSongTitle"
    multiroom_wifidirect: False
    sources:
      {
        "optical": "TV sound",
        "line-in": "Radio tuner",
        "bluetooth": "Bluetooth",
        "udisk": "USB stick",
        "http://94.199.183.186:8000/jazzy-soul.mp3": "Jazzy Soul",
      }`

The check config wheel spins indefinately.

The output of the log file:

`Logger: aiohttp.server
Kilde: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
Førs oppstått: 13:36:54 (8 hendelser)
Sist logget: 14:23:29

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/core.py", line 38, in post
    res = await check_config.async_check_ha_config_file(request.app[KEY_HASS])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 274, in async_check_ha_config_file
    platform = await p_integration.async_get_platform(domain)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_asyncio.Future' object has no attribute 'async_get_platform'`

**Comment by nagyrobi** [comment]
Why do you think it's related to linkplay?

**Comment by borgeST** [comment]
As when removing the entry above in config, the check config is checked green

**Comment by nagyrobi** [comment]
There's no indication in that log excerpt that it's linkplay-related....
For me, it works with all my players. There must be something else in your case.

**Comment by borgeST** [comment]
Ok, will continue to search, or disable it
