### ISSUE TITLE
Please support the smart speaker which is using Linkplay A98 module to play Youtube media stream.

### ISSUE THREAD

**Issue by dinhchinh82** [nagyrobi/media_player.linkplay#149]
I just tried to add a smart speaker which using [Linkplay A98 module](https://www.linkplay.com/modules-wifi) to Home Assistant via latest Linkplay custom component (version 3.2.2) but it did not work well.
After adding the speaker to HA, it can show as a media player and Text to Speech works well, can play local mp3 file etc.

By the way, when I tried to play a Youtube song or a playlist, it did not work.
The codec of Youtube media file is "video/mp4; codecs=\"avc1.42001E, mp4a.40.2\".
For speaker using Linkplay A31 module, it works well with Youtube.
So is able to support to play Youtube on the speakers using A98 module?

Thank you.
---
Here is the log from HA when I play an Youtube media file.

> 2024-07-30 16:10:23.282 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547799696832] Entity media_player.da_vung_43_2 does not support this service.
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2543, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2580, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 953, in entity_service_call
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity media_player.da_vung_43_2 does not support this service.
2024-07-30 16:10:24.319 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547799696832] Entity media_player.da_vung_43_2 does not support this service.
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2543, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2580, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 953, in entity_service_call
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity media_player.da_vung_43_2 does not support this service.
2024-07-30 16:10:25.905 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547799696832] Entity media_player.da_vung_43_2 does not support this service.
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2543, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2580, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 953, in entity_service_call
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity media_player.da_vung_43_2 does not support this service.

**Comment by nagyrobi** [comment]
I don't have a Linkplay A98 to test, sorry.

**Comment by dinhchinh82** [comment]
> I don't have a Linkplay A98 to test, sorry.

@nagyrobi I can help you to test. how do you think if I can give you the ssh & remote URL fo access HA which already linked the Linkplay A98 speaker? Please give me your email or telegram/discord account then I can contact you directly.

**Comment by nagyrobi** [comment]
Not willing to enter third party networks, sorry.

**Comment by dinhchinh82** [comment]
> Not willing to enter third party networks, sorry.

@nagyrobi Could you suggest any solution to debug it remotely? is able to send you the log to debug or anything?

**Comment by nagyrobi** [comment]
**From now, the `linkplay` custom component for Home Assistant is deprecated, and unsupported! Starting with Home Assistant 2024.08 release, Linkplay chipset based media players are officially supported without the need of any custom component.**

To switch tho the official LinkPlay integration starting from **2024.08**, follow these steps:
* Remove tle current `linkplay` configuration to your configuration.yaml.
* Restart Home-Assistant.
* Delete the custom component through HACS or manually by deleting the `custom_components/linkplay` folder.
* Restart Home-Assistant again. Your players will be automatically discovered by Home Assistant, a notification popup will inform you on this.

For any bugs and feature requests, please use the official Home Assistant channels.
