### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by lucasimons** [nagyrobi/media_player.linkplay#85]
the player works fine but i have this worning

```
Logger: homeassistant.helpers.entity
Source: custom_components/linkplay/media_player.py:441
Integration: Linkplay ([documentation](https://github.com/nagyrobi/home-assistant-custom-components-linkplay), [issues](https://github.com/nagyrobi/home-assistant-custom-components-linkplay/issues))
First occurred: 18:39:30 (61 occurrences)
Last logged: 18:42:21

Update for media_player.seeme_hifi fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/config/custom_components/linkplay/media_player.py", line 560, in async_update
    await self.async_get_status(no_throttle=True)
  File "/config/custom_components/linkplay/media_player.py", line 490, in async_get_status
    resp = await self.async_call_linkplay_httpapi("getPlayerStatus", True)
  File "/config/custom_components/linkplay/media_player.py", line 441, in async_call_linkplay_httpapi
    data = await response.json(content_type=None)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 134 (char 133)

```

**Comment by nagyrobi** [comment]
Seems like the API of your player is different.

Please post output of:
http://your.player.ip/httpapi.asp?command=getStatusEx
http://your.player.ip/httpapi.asp?command=getStatus

**Comment by lucasimons** [comment]
the problem is an automation if i use this service doesen t work
```
service: tts.google_say
data:
  entity_id: media_player.seeme_hifi
  message: la potenza attuale è {{states('sensor.potenza') | int}}  watt
  language: it
  cache: false
```

instead if i use this, it works fine

```
service: tts.google_say
data:
  entity_id: media_player.seeme_hifi
  message: la potenza  è {{states('sensor.potenza') | int}}  watt
  language: it
  cache: false
```

i recently update HA to 

Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest


if i use a different speaker works but if i use the speacker connected with linkplay give me the error

**Comment by lucasimons** [comment]
There is something strange with some character or word?

```
File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 134 (char 133)

```


```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/config/custom_components/linkplay/media_player.py", line 560, in async_update
    await self.async_get_status(no_throttle=True)
  File "/config/custom_components/linkplay/media_player.py", line 490, in async_get_status
    resp = await self.async_call_linkplay_httpapi("getPlayerStatus", True)
  File "/config/custom_components/linkplay/media_player.py", line 441, in async_call_linkplay_httpapi
    data = await response.json(content_type=None)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 131: invalid start byte 

```

**Comment by nagyrobi** [comment]
Closind due to missing information.
